version: "3.8"

# https://stackoverflow.com/questions/31425838/bash-with-aws-cli-unable-to-locate-credentials

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 wsgi:application
    ports:
      - "8000:8000"
    volumes:
      - /home/asdasdaasd/.aws/:/root/.aws/:ro